#!/bin/bash

# From: https://github.com/OSInside/kiwi/blob/v9.23.20/kiwi/config/functions.sh
# Or: /usr/lib/python3.6/site-packages/kiwi/config/functions.sh (python3-kiwi package)
function baseUpdateSysConfig {
    # /.../
    # Update the contents of a sysconfig variable
    # ----
    local FILE=$1
    local VAR
    local VAL
    if [ -f "${FILE}" ];then
        VAR=$2
        VAL=$3
        eval sed -i "s'@^\($VAR=\).*\$@\1\\\"$VAL\\\"@'" "${FILE}"
    else
        echo "warning: config file $FILE not found"
    fi
}

SELECTED_LANGUAGE=$1

# Set locale
/usr/sbin/langset.sh $SELECTED_LANGUAGE

case "$SELECTED_LANGUAGE" in
    en_US)
        baseUpdateSysConfig /etc/sysconfig/keyboard YAST_KEYBOARD "english-us,pc104"
        #baseUpdateSysConfig /etc/sysconfig/clock DEFAULT_TIMEZONE "US/Eastern"
        echo "DEFAULT_TIMEZONE=\"US/Eastern\"" >> /etc/sysconfig/clock
        rm /etc/adjtime
        break
        ;;

    pt_BR)
        baseUpdateSysConfig /etc/sysconfig/keyboard YAST_KEYBOARD "portugese-br,pc104"
        baseUpdateSysConfig /etc/sysconfig/language RC_LANG "pt_BR.UTF-8"
        baseUpdateSysConfig /etc/sysconfig/language ROOT_USES_LANG "yes"
        baseUpdateSysConfig /etc/sysconfig/language INSTALLED_LANGUAGES "pt_BR"
        #baseUpdateSysConfig /etc/sysconfig/clock DEFAULT_TIMEZONE "Brazil/East"
        echo "DEFAULT_TIMEZONE=\"Brazil/East\"" >> /etc/sysconfig/clock
        echo "pool pool.ntp.br iburst" > /etc/chrony.d/pool.conf
        break
        ;;
    esac

